spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/db_springboot_cloud?serverTimezone=Europe/Madrid
    username: root
    password: atleti1983
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect